"""Gate 2 GRPO trainer for the multifield DISCLOSURE task (runs ON the H20).

Reuses the validated multifield domain + episode from `src` (shipped alongside, plus the small
InjecAgent data dir). The frozen victim + the base follow-up attacker are both served via the
SiliconFlow API (so the 27B never touches the H20 disk; only the trained Qwen3-8B is local).

GRPO samples the attacker's OPENING message; reward_fn runs the full T-turn extraction episode with
that opening as turn 1 and turns 2..T generated by the FIXED base Qwen3-8B (API), then returns:
  dense  = max_t Phi_t   = (# distinct field values disclosed)/K   (per-step / process reward)
  sparse = 1.0 if any turn reached Phi >= tau else 0.0             (terminal / outcome reward)
This is the Gate-2 mechanism check: do both arms learn, and does dense diverge (chase partial Phi)?

  SILICONFLOW_API_KEY=... SILICONFLOW_BASE_URL=... \
  python h1_grpo_train_extract.py --arm dense --steps 20 --seed 0 --T 3
"""
from __future__ import annotations

import argparse
import json
import sys
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

import torch
from datasets import Dataset
from peft import LoraConfig
from transformers import BitsAndBytesConfig, TrainerCallback
from trl import GRPOConfig, GRPOTrainer

HERE = Path(__file__).resolve().parent
SRC = HERE.parent / "src"
sys.path.insert(0, str(SRC.parent))  # so `import src...` works
sys.path.insert(0, str(SRC))

from src.attacker import build_initial_messages  # noqa: E402
from src.direct_extraction_episode import run_direct_extraction_episode  # noqa: E402
from src.domains.extraction_multifield import MultiFieldExtractionDomain  # noqa: E402
from src.trace import LoggedClient, TraceLogger  # noqa: E402

ATTACKER_MODEL = "Qwen/Qwen3-8B"                       # trained locally (4-bit QLoRA)
ATTACKER_SPEC = {"provider": "siliconflow", "model": "Qwen/Qwen3-8B",   # fixed base follow-up (turns 2..T)
                 "max_tokens": 1024, "temperature": 0.8, "enable_thinking": False}
VICTIM_SPEC = {"provider": "siliconflow", "model": "Qwen/Qwen3.6-27B",
               "max_tokens": 512, "temperature": 0.7, "enable_thinking": False}

G = {}  # globals wired in main(), read by reward_fn


def parse_opening(completion) -> str:
    from src.attacker import parse_injection
    content = (completion[0]["content"] if isinstance(completion, list) else completion) or ""
    return parse_injection(content)


def reward_fn(completions, **kwargs):
    gidxs = kwargs["gidx"]

    def score(i, completion):
        opening = parse_opening(completion)
        goal = G["goals"][int(gidxs[i])]
        rec = run_direct_extraction_episode(
            G["dom"], goal, G["client"], ATTACKER_SPEC, G["client"], VICTIM_SPEC,
            T=G["T"], max_calls=1, arm=G["arm"], seed=0, trace=G["trace"],
            sample_idx=i, reward_mode="final", first_message=opening)
        G["trace"].log_record({"kind": "train_rollout", "arm": G["arm"], "goal": goal.id,
                               "reward": rec["reward"], "max_phi": rec["max_phi"],
                               "success": rec["success"], "n_turns": rec["n_turns"],
                               "refused": len(opening.strip()) < 3, "opening": opening[:280]})
        return float(rec["reward"])

    with ThreadPoolExecutor(max_workers=G["workers"]) as ex:
        return list(ex.map(lambda a: score(*a), enumerate(completions)))


class ProgressCallback(TrainerCallback):
    def __init__(self, path, arm, seed):
        self.path, self.meta = path, {"arm": arm, "seed": seed}

    def on_log(self, args, state, control, logs=None, **kw):
        if not logs:
            return
        rec = {"step": state.global_step, **self.meta,
               **{k: round(v, 5) for k, v in logs.items() if isinstance(v, (int, float))}}
        with open(self.path, "a", encoding="utf-8") as f:
            f.write(json.dumps(rec) + "\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--arm", choices=["sparse", "dense"], required=True)
    ap.add_argument("--steps", type=int, default=20)
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--T", type=int, default=3)
    ap.add_argument("--K", type=int, default=5)
    ap.add_argument("--tau", type=float, default=1.0)
    ap.add_argument("--defense", default="light")
    ap.add_argument("--n-train", type=int, default=48)
    ap.add_argument("--num-gen", type=int, default=5)
    ap.add_argument("--workers", type=int, default=8)
    ap.add_argument("--run-root", default="/root/autodl-tmp/h1x")
    ap.add_argument("--smoke", action="store_true")
    ap.add_argument("--tag", default="")
    args = ap.parse_args()

    tag = args.tag or f"extract-{args.arm}-s{args.seed}"
    run_root = Path(args.run_root)
    run_dir = run_root / "runs" / tag
    trace = TraceLogger(run_dir)
    client = LoggedClient(trace)

    dom = MultiFieldExtractionDomain(K=args.K, tau=args.tau, defense_tier=args.defense)
    n = 6 if args.smoke else args.n_train
    goals = dom.load_goals("indomain", seed=0, n=n)
    G.update(arm=args.arm, dom=dom, goals=goals, client=client, trace=trace, T=args.T, workers=args.workers)

    ds = Dataset.from_list([{"prompt": build_initial_messages(dom, g), "gidx": i}
                            for i, g in enumerate(goals)])

    from transformers import AutoModelForCausalLM, AutoTokenizer
    tok = AutoTokenizer.from_pretrained(ATTACKER_MODEL)
    bnb = BitsAndBytesConfig(load_in_4bit=True, bnb_4bit_quant_type="nf4",
                             bnb_4bit_use_double_quant=True, bnb_4bit_compute_dtype=torch.bfloat16)
    lora = LoraConfig(r=32, lora_alpha=64, lora_dropout=0.0, bias="none", task_type="CAUSAL_LM",
                      target_modules=["q_proj", "k_proj", "v_proj", "o_proj",
                                      "gate_proj", "up_proj", "down_proj"])
    cfg = GRPOConfig(
        output_dir=str(run_dir / "ckpt"),
        use_vllm=False, num_generations=args.num_gen,
        per_device_train_batch_size=args.num_gen, gradient_accumulation_steps=4,
        num_iterations=1, max_completion_length=256,
        temperature=1.0, beta=0.0, scale_rewards=False, loss_type="dr_grpo",
        learning_rate=1e-5, max_steps=args.steps, logging_steps=1,
        save_steps=1000, save_total_limit=1,
        bf16=True, report_to="none", seed=args.seed,
        chat_template_kwargs={"enable_thinking": False},
    )
    model = AutoModelForCausalLM.from_pretrained(
        ATTACKER_MODEL, quantization_config=bnb, torch_dtype=torch.bfloat16, device_map={"": 0})
    trainer = GRPOTrainer(model=model, args=cfg, peft_config=lora, reward_funcs=reward_fn,
                          train_dataset=ds, processing_class=tok)
    trainer.add_callback(ProgressCallback(str(run_root / "progress.jsonl"), args.arm, args.seed))
    print(f"[grpo-x] cell={tag} arm={args.arm} steps={args.steps} T={args.T} n_train={len(ds)} "
          f"G={args.num_gen} tau={args.tau} defense={args.defense} victim={VICTIM_SPEC['model']}@API")
    trainer.train()
    trainer.save_model(str(run_dir / "adapter"))
    trace.close()
    print(f"[grpo-x] DONE cell={tag} -> {run_dir}")


if __name__ == "__main__":
    main()
